// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0496136066f732e49a736cdfcb96bdb9_6473fd52feaf4836a518bbb0c1df46b9 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0496136066f732e49a736cdfcb96bdb9_51b4d55810db4625b9e21e35055e56e8 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0496136066f732e49a736cdfcb96bdb9_6bc895f6c58f4b2baf9ad2294ec16dbd : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0496136066f732e49a736cdfcb96bdb9_1990340933530280939);
        public override string CoherenceComponentName => "_0496136066f732e49a736cdfcb96bdb9_1990340933530280939";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent).isBeingPushed;

            var simFrame = ((_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0496136066f732e49a736cdfcb96bdb9_1990340933530280939();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0496136066f732e49a736cdfcb96bdb9_8d68a42b4d4046d9b5417198f39eba4d : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0496136066f732e49a736cdfcb96bdb9_1990340933530280939);
        public override string CoherenceComponentName => "_0496136066f732e49a736cdfcb96bdb9_1990340933530280939";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent).isBeingPulled;

            var simFrame = ((_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0496136066f732e49a736cdfcb96bdb9_1990340933530280939();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_0496136066f732e49a736cdfcb96bdb9_390c34b888af40f7a90beed8390b2b78 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0496136066f732e49a736cdfcb96bdb9_1990340933530280939);
        public override string CoherenceComponentName => "_0496136066f732e49a736cdfcb96bdb9_1990340933530280939";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent).isFalling;

            var simFrame = ((_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0496136066f732e49a736cdfcb96bdb9_1990340933530280939)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0496136066f732e49a736cdfcb96bdb9_1990340933530280939();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0496136066f732e49a736cdfcb96bdb9 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0496136066f732e49a736cdfcb96bdb9>();
        
        private global::Obstacle _0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["6473fd52feaf4836a518bbb0c1df46b9"] = new Binding_0496136066f732e49a736cdfcb96bdb9_6473fd52feaf4836a518bbb0c1df46b9(),
			["51b4d55810db4625b9e21e35055e56e8"] = new Binding_0496136066f732e49a736cdfcb96bdb9_51b4d55810db4625b9e21e35055e56e8(),
			["6bc895f6c58f4b2baf9ad2294ec16dbd"] = new Binding_0496136066f732e49a736cdfcb96bdb9_6bc895f6c58f4b2baf9ad2294ec16dbd(),
			["8d68a42b4d4046d9b5417198f39eba4d"] = new Binding_0496136066f732e49a736cdfcb96bdb9_8d68a42b4d4046d9b5417198f39eba4d(),
			["390c34b888af40f7a90beed8390b2b78"] = new Binding_0496136066f732e49a736cdfcb96bdb9_390c34b888af40f7a90beed8390b2b78(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0496136066f732e49a736cdfcb96bdb9()
        {
            bakedCommandBindings.Add("def871c55cc742de9988ac8452905d66", BakeCommandBinding__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66,
            	ReceiveLocalCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66,
            	MessageTarget.All,
            	_0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66(command);
        }

        private void ReceiveCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66(_0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66 command)
        {
			var target = _0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66 castedCommand:
                    ReceiveCommand__0496136066f732e49a736cdfcb96bdb9_def871c55cc742de9988ac8452905d66(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0496136066f732e49a736cdfcb96bdb9 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0496136066f732e49a736cdfcb96bdb9>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
