// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1908b8b6291f24f4f90d5bd631b848b8_f1230e9bce5e4b2cae1f8c76eac24f59 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1908b8b6291f24f4f90d5bd631b848b8_33cc0cb6f4f243a4be41a3d0c80c7d29 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1908b8b6291f24f4f90d5bd631b848b8_05cc537d638645109e4a86e7b43616a0 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288);
        public override string CoherenceComponentName => "_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent).isBeingPushed;

            var simFrame = ((_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1908b8b6291f24f4f90d5bd631b848b8_fdf5a092b7904f68b2ba1e6876814d48 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288);
        public override string CoherenceComponentName => "_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent).isBeingPulled;

            var simFrame = ((_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1908b8b6291f24f4f90d5bd631b848b8_c627d37e072a4a83a59dc7fe88b43503 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288);
        public override string CoherenceComponentName => "_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent).isFalling;

            var simFrame = ((_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1908b8b6291f24f4f90d5bd631b848b8_6538309201168886288();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_1908b8b6291f24f4f90d5bd631b848b8 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_1908b8b6291f24f4f90d5bd631b848b8>();
        
        private global::Obstacle _1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450_CommandTarget;
        private global::Obstacle _1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["f1230e9bce5e4b2cae1f8c76eac24f59"] = new Binding_1908b8b6291f24f4f90d5bd631b848b8_f1230e9bce5e4b2cae1f8c76eac24f59(),
			["33cc0cb6f4f243a4be41a3d0c80c7d29"] = new Binding_1908b8b6291f24f4f90d5bd631b848b8_33cc0cb6f4f243a4be41a3d0c80c7d29(),
			["05cc537d638645109e4a86e7b43616a0"] = new Binding_1908b8b6291f24f4f90d5bd631b848b8_05cc537d638645109e4a86e7b43616a0(),
			["fdf5a092b7904f68b2ba1e6876814d48"] = new Binding_1908b8b6291f24f4f90d5bd631b848b8_fdf5a092b7904f68b2ba1e6876814d48(),
			["c627d37e072a4a83a59dc7fe88b43503"] = new Binding_1908b8b6291f24f4f90d5bd631b848b8_c627d37e072a4a83a59dc7fe88b43503(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_1908b8b6291f24f4f90d5bd631b848b8()
        {
            bakedCommandBindings.Add("85243f86d85d4c0497df9eda158f8450", BakeCommandBinding__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450);
            bakedCommandBindings.Add("d2ef13201b5f4d959a64f340c132756e", BakeCommandBinding__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450,
            	ReceiveLocalCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450,
            	MessageTarget.All,
            	_1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450(command);
        }

        private void ReceiveCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450(_1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450 command)
        {
			var target = _1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e,
            	ReceiveLocalCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e,
            	MessageTarget.All,
            	_1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e(command);
        }

        private void ReceiveCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e(_1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e command)
        {
			var target = _1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450 castedCommand:
                    ReceiveCommand__1908b8b6291f24f4f90d5bd631b848b8_85243f86d85d4c0497df9eda158f8450(castedCommand);
                    break;
                case _1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e castedCommand:
                    ReceiveCommand__1908b8b6291f24f4f90d5bd631b848b8_d2ef13201b5f4d959a64f340c132756e(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_1908b8b6291f24f4f90d5bd631b848b8 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_1908b8b6291f24f4f90d5bd631b848b8>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
