// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_9a93e5716c62e0c4ba4e26102c13d2f5_88169a89f0164f03ac5fc84f9a57338e : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_9a93e5716c62e0c4ba4e26102c13d2f5_e5501ffe3ee94c6784cb9dc1dff18c18 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_9a93e5716c62e0c4ba4e26102c13d2f5_83e04ed41d6244cf8d6c67456fff6ecd : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043);
        public override string CoherenceComponentName => "_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent).isBeingPushed;

            var simFrame = ((_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_9a93e5716c62e0c4ba4e26102c13d2f5_37867126b3f74fd49d460eda92088335 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043);
        public override string CoherenceComponentName => "_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent).isBeingPulled;

            var simFrame = ((_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_9a93e5716c62e0c4ba4e26102c13d2f5_d1082c66d2e34413afd422edb20497fb : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043);
        public override string CoherenceComponentName => "_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent).isFalling;

            var simFrame = ((_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _9a93e5716c62e0c4ba4e26102c13d2f5_3032056999160085043();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_9a93e5716c62e0c4ba4e26102c13d2f5 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_9a93e5716c62e0c4ba4e26102c13d2f5>();
        
        private global::Obstacle _9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b_CommandTarget;
        private global::Obstacle _9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["88169a89f0164f03ac5fc84f9a57338e"] = new Binding_9a93e5716c62e0c4ba4e26102c13d2f5_88169a89f0164f03ac5fc84f9a57338e(),
			["e5501ffe3ee94c6784cb9dc1dff18c18"] = new Binding_9a93e5716c62e0c4ba4e26102c13d2f5_e5501ffe3ee94c6784cb9dc1dff18c18(),
			["83e04ed41d6244cf8d6c67456fff6ecd"] = new Binding_9a93e5716c62e0c4ba4e26102c13d2f5_83e04ed41d6244cf8d6c67456fff6ecd(),
			["37867126b3f74fd49d460eda92088335"] = new Binding_9a93e5716c62e0c4ba4e26102c13d2f5_37867126b3f74fd49d460eda92088335(),
			["d1082c66d2e34413afd422edb20497fb"] = new Binding_9a93e5716c62e0c4ba4e26102c13d2f5_d1082c66d2e34413afd422edb20497fb(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_9a93e5716c62e0c4ba4e26102c13d2f5()
        {
            bakedCommandBindings.Add("d78a133fc87c4e53934451de4e19d40b", BakeCommandBinding__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b);
            bakedCommandBindings.Add("cbadccff5c5348bc8182d2233c0df6dd", BakeCommandBinding__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b,
            	ReceiveLocalCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b,
            	MessageTarget.All,
            	_9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b(command);
        }

        private void ReceiveCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b(_9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b command)
        {
			var target = _9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd,
            	ReceiveLocalCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd,
            	MessageTarget.All,
            	_9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd(GenericCommandRequestArgs requestArgs)
        {
            var command = new _9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd(GenericCommandRequestArgs requestArgs)
        {
            var command = new _9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd(command);
        }

        private void ReceiveCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd(_9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd command)
        {
			var target = _9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b castedCommand:
                    ReceiveCommand__9a93e5716c62e0c4ba4e26102c13d2f5_d78a133fc87c4e53934451de4e19d40b(castedCommand);
                    break;
                case _9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd castedCommand:
                    ReceiveCommand__9a93e5716c62e0c4ba4e26102c13d2f5_cbadccff5c5348bc8182d2233c0df6dd(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_9a93e5716c62e0c4ba4e26102c13d2f5 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_9a93e5716c62e0c4ba4e26102c13d2f5>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
