// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_2475f3281c4c426f8a69b307ef2fa1ed : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_7c3dae0296d14eceaeb60826b077d1d9 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_26a8adadf777410bbd31c94fad45d7b6 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Walking;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).WalkingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Walking = Value;
            }
            else
            {
                update.Walking = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.WalkingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_5bf63d17893242bf90b433e3e7ec7b69 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Push;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).PushSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Push = Value;
            }
            else
            {
                update.Push = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.PushSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_ed3712442e454f44823418d36ae44b47 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Jumping;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).JumpingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Jumping = Value;
            }
            else
            {
                update.Jumping = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.JumpingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_8cfa57f36ff34d4e893b48d7352f2a85 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Pull;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).PullSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Pull = Value;
            }
            else
            {
                update.Pull = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.PullSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_4c27613c2be14438b046e7f00516eaae : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Hit;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).HitSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Hit = Value;
            }
            else
            {
                update.Hit = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.HitSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_45baea24fbba42e1a83eb415d4c39467 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000000100000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).HitDown;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).HitDownSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.HitDown = Value;
            }
            else
            {
                update.HitDown = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.HitDownSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_fd1ba7d127ab4d5bb5b42c6b803e40f4 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000001000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).HitSpecial;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).HitSpecialSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.HitSpecial = Value;
            }
            else
            {
                update.HitSpecial = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.HitSpecialSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_e7a46ec6a9fa4df2be78f567d123c0b7 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000010000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Falling;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).FallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Falling = Value;
            }
            else
            {
                update.Falling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.FallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_575fad77ef664b52a7150ab7f6e62aa4 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000000100000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Grounded;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).GroundedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Grounded = Value;
            }
            else
            {
                update.Grounded = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.GroundedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_50848e819bf04a518f49bef1b055774e : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000001000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Idle;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).IdleSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Idle = Value;
            }
            else
            {
                update.Idle = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IdleSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_4f7df5f6ec0c43aeb7c28bc284214d0f : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000010000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).LookRight;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).LookRightSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.LookRight = Value;
            }
            else
            {
                update.LookRight = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.LookRightSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_325e2907553940639ca70ba8c78a9997 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000000100000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).LookLeft;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).LookLeftSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.LookLeft = Value;
            }
            else
            {
                update.LookLeft = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.LookLeftSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_5c5a779d77c9486895627dea9d4d9639 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000001000000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Running;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).RunningSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Running = Value;
            }
            else
            {
                update.Running = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.RunningSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6fbc467c14a340499ee5aae55a3519c_77a1b41ac2274915898ef6824b95afc5 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810);
        public override string CoherenceComponentName => "_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810";
        public override uint FieldMask => 0b00000000000000000010000000000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).Dead;

            var simFrame = ((_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent).DeadSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6fbc467c14a340499ee5aae55a3519c_2197336975981693810)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Dead = Value;
            }
            else
            {
                update.Dead = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.DeadSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6fbc467c14a340499ee5aae55a3519c_2197336975981693810();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_b6fbc467c14a340499ee5aae55a3519c : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_b6fbc467c14a340499ee5aae55a3519c>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["2475f3281c4c426f8a69b307ef2fa1ed"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_2475f3281c4c426f8a69b307ef2fa1ed(),
			["7c3dae0296d14eceaeb60826b077d1d9"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_7c3dae0296d14eceaeb60826b077d1d9(),
			["26a8adadf777410bbd31c94fad45d7b6"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_26a8adadf777410bbd31c94fad45d7b6(),
			["5bf63d17893242bf90b433e3e7ec7b69"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_5bf63d17893242bf90b433e3e7ec7b69(),
			["ed3712442e454f44823418d36ae44b47"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_ed3712442e454f44823418d36ae44b47(),
			["8cfa57f36ff34d4e893b48d7352f2a85"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_8cfa57f36ff34d4e893b48d7352f2a85(),
			["4c27613c2be14438b046e7f00516eaae"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_4c27613c2be14438b046e7f00516eaae(),
			["45baea24fbba42e1a83eb415d4c39467"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_45baea24fbba42e1a83eb415d4c39467(),
			["fd1ba7d127ab4d5bb5b42c6b803e40f4"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_fd1ba7d127ab4d5bb5b42c6b803e40f4(),
			["e7a46ec6a9fa4df2be78f567d123c0b7"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_e7a46ec6a9fa4df2be78f567d123c0b7(),
			["575fad77ef664b52a7150ab7f6e62aa4"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_575fad77ef664b52a7150ab7f6e62aa4(),
			["50848e819bf04a518f49bef1b055774e"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_50848e819bf04a518f49bef1b055774e(),
			["4f7df5f6ec0c43aeb7c28bc284214d0f"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_4f7df5f6ec0c43aeb7c28bc284214d0f(),
			["325e2907553940639ca70ba8c78a9997"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_325e2907553940639ca70ba8c78a9997(),
			["5c5a779d77c9486895627dea9d4d9639"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_5c5a779d77c9486895627dea9d4d9639(),
			["77a1b41ac2274915898ef6824b95afc5"] = new Binding_b6fbc467c14a340499ee5aae55a3519c_77a1b41ac2274915898ef6824b95afc5(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_b6fbc467c14a340499ee5aae55a3519c()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_b6fbc467c14a340499ee5aae55a3519c Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_b6fbc467c14a340499ee5aae55a3519c>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
