// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_df2f29af56c91bd4f9755f5056262669_c9d9d4cda6a04f808878485ac1010e5b : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_df2f29af56c91bd4f9755f5056262669_db597b590eb6467996e382a173242520 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_df2f29af56c91bd4f9755f5056262669_7ea29d9c9802411eaaed939b4dc6abac : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_df2f29af56c91bd4f9755f5056262669_5616364818191066812);
        public override string CoherenceComponentName => "_df2f29af56c91bd4f9755f5056262669_5616364818191066812";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent).isBeingPushed;

            var simFrame = ((_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _df2f29af56c91bd4f9755f5056262669_5616364818191066812();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_df2f29af56c91bd4f9755f5056262669_2e3cb78eb05a4881b8061f48905afa11 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_df2f29af56c91bd4f9755f5056262669_5616364818191066812);
        public override string CoherenceComponentName => "_df2f29af56c91bd4f9755f5056262669_5616364818191066812";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent).isBeingPulled;

            var simFrame = ((_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _df2f29af56c91bd4f9755f5056262669_5616364818191066812();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_df2f29af56c91bd4f9755f5056262669_2bea7d8d1a3a4974aa8e3654c7c853db : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_df2f29af56c91bd4f9755f5056262669_5616364818191066812);
        public override string CoherenceComponentName => "_df2f29af56c91bd4f9755f5056262669_5616364818191066812";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent).isFalling;

            var simFrame = ((_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_df2f29af56c91bd4f9755f5056262669_5616364818191066812)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _df2f29af56c91bd4f9755f5056262669_5616364818191066812();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_df2f29af56c91bd4f9755f5056262669 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_df2f29af56c91bd4f9755f5056262669>();
        
        private global::Obstacle _df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074_CommandTarget;
        private global::Obstacle _df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["c9d9d4cda6a04f808878485ac1010e5b"] = new Binding_df2f29af56c91bd4f9755f5056262669_c9d9d4cda6a04f808878485ac1010e5b(),
			["db597b590eb6467996e382a173242520"] = new Binding_df2f29af56c91bd4f9755f5056262669_db597b590eb6467996e382a173242520(),
			["7ea29d9c9802411eaaed939b4dc6abac"] = new Binding_df2f29af56c91bd4f9755f5056262669_7ea29d9c9802411eaaed939b4dc6abac(),
			["2e3cb78eb05a4881b8061f48905afa11"] = new Binding_df2f29af56c91bd4f9755f5056262669_2e3cb78eb05a4881b8061f48905afa11(),
			["2bea7d8d1a3a4974aa8e3654c7c853db"] = new Binding_df2f29af56c91bd4f9755f5056262669_2bea7d8d1a3a4974aa8e3654c7c853db(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_df2f29af56c91bd4f9755f5056262669()
        {
            bakedCommandBindings.Add("18c40f0fdc5746bd8cdbb10126a20074", BakeCommandBinding__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074);
            bakedCommandBindings.Add("c0aaff7f54c849608bf2f1417c0a9761", BakeCommandBinding__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074,
            	ReceiveLocalCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074,
            	MessageTarget.All,
            	_df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074(GenericCommandRequestArgs requestArgs)
        {
            var command = new _df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074(GenericCommandRequestArgs requestArgs)
        {
            var command = new _df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074(command);
        }

        private void ReceiveCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074(_df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074 command)
        {
			var target = _df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761,
            	ReceiveLocalCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761,
            	MessageTarget.All,
            	_df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761(GenericCommandRequestArgs requestArgs)
        {
            var command = new _df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761(GenericCommandRequestArgs requestArgs)
        {
            var command = new _df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761(command);
        }

        private void ReceiveCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761(_df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761 command)
        {
			var target = _df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074 castedCommand:
                    ReceiveCommand__df2f29af56c91bd4f9755f5056262669_18c40f0fdc5746bd8cdbb10126a20074(castedCommand);
                    break;
                case _df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761 castedCommand:
                    ReceiveCommand__df2f29af56c91bd4f9755f5056262669_c0aaff7f54c849608bf2f1417c0a9761(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_df2f29af56c91bd4f9755f5056262669 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_df2f29af56c91bd4f9755f5056262669>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
