// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_098926bb6b75f084399b837695195d5f_f83b9e92d90d4f9892aced4369db6852 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_098926bb6b75f084399b837695195d5f : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_098926bb6b75f084399b837695195d5f>();
        
        private global::LevelGoal _098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b_CommandTarget;
        private global::LevelGoal _098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["f83b9e92d90d4f9892aced4369db6852"] = new Binding_098926bb6b75f084399b837695195d5f_f83b9e92d90d4f9892aced4369db6852(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_098926bb6b75f084399b837695195d5f()
        {
            bakedCommandBindings.Add("6a7fd819b64c4859972d161574c08a9b", BakeCommandBinding__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b);
            bakedCommandBindings.Add("28bec6945452444bab5754c7bbc0ae0a", BakeCommandBinding__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b_CommandTarget = (global::LevelGoal)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"LevelGoal.CmdLoseLevel",
            	"()",
            	SendCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b,
            	ReceiveLocalCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b,
            	MessageTarget.All,
            	_098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b(command);
        }

        private void ReceiveCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b(_098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b command)
        {
			var target = _098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b_CommandTarget;
			target.CmdLoseLevel();
        }
        private void BakeCommandBinding__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a_CommandTarget = (global::LevelGoal)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"LevelGoal.CmdWinLevel",
            	"()",
            	SendCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a,
            	ReceiveLocalCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a,
            	MessageTarget.All,
            	_098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a(GenericCommandRequestArgs requestArgs)
        {
            var command = new _098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a(GenericCommandRequestArgs requestArgs)
        {
            var command = new _098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a(command);
        }

        private void ReceiveCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a(_098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a command)
        {
			var target = _098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a_CommandTarget;
			target.CmdWinLevel();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b castedCommand:
                    ReceiveCommand__098926bb6b75f084399b837695195d5f_6a7fd819b64c4859972d161574c08a9b(castedCommand);
                    break;
                case _098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a castedCommand:
                    ReceiveCommand__098926bb6b75f084399b837695195d5f_28bec6945452444bab5754c7bbc0ae0a(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_098926bb6b75f084399b837695195d5f Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_098926bb6b75f084399b837695195d5f>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
