// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_8303c37f41e9c994e8c222f3506bbb77_8b423ac22e62423eb8d39c6618a9a444 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_8303c37f41e9c994e8c222f3506bbb77 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_8303c37f41e9c994e8c222f3506bbb77>();
        
        private global::LevelGoal _8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429_CommandTarget;
        private global::LevelGoal _8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["8b423ac22e62423eb8d39c6618a9a444"] = new Binding_8303c37f41e9c994e8c222f3506bbb77_8b423ac22e62423eb8d39c6618a9a444(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_8303c37f41e9c994e8c222f3506bbb77()
        {
            bakedCommandBindings.Add("e72b475cc9cb4c1dbc40d23d465f8429", BakeCommandBinding__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429);
            bakedCommandBindings.Add("28064e1d39ca4285a63567a7d20e232d", BakeCommandBinding__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429_CommandTarget = (global::LevelGoal)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"LevelGoal.CmdLoseLevel",
            	"()",
            	SendCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429,
            	ReceiveLocalCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429,
            	MessageTarget.All,
            	_8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429(command);
        }

        private void ReceiveCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429(_8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429 command)
        {
			var target = _8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429_CommandTarget;
			target.CmdLoseLevel();
        }
        private void BakeCommandBinding__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d_CommandTarget = (global::LevelGoal)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"LevelGoal.CmdWinLevel",
            	"()",
            	SendCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d,
            	ReceiveLocalCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d,
            	MessageTarget.All,
            	_8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d(GenericCommandRequestArgs requestArgs)
        {
            var command = new _8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d(command);
        }

        private void ReceiveCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d(_8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d command)
        {
			var target = _8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d_CommandTarget;
			target.CmdWinLevel();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429 castedCommand:
                    ReceiveCommand__8303c37f41e9c994e8c222f3506bbb77_e72b475cc9cb4c1dbc40d23d465f8429(castedCommand);
                    break;
                case _8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d castedCommand:
                    ReceiveCommand__8303c37f41e9c994e8c222f3506bbb77_28064e1d39ca4285a63567a7d20e232d(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_8303c37f41e9c994e8c222f3506bbb77 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_8303c37f41e9c994e8c222f3506bbb77>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
