// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_7ad02c873b170db439e210ad7dcb4450_700c608d754741d89c35d54a1a3e7df0 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_7ad02c873b170db439e210ad7dcb4450_00d6b3670f0844c4bcaae3d48346deb5 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_7ad02c873b170db439e210ad7dcb4450 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_7ad02c873b170db439e210ad7dcb4450>();
        
        private global::PowerupCollectible _7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["700c608d754741d89c35d54a1a3e7df0"] = new Binding_7ad02c873b170db439e210ad7dcb4450_700c608d754741d89c35d54a1a3e7df0(),
			["00d6b3670f0844c4bcaae3d48346deb5"] = new Binding_7ad02c873b170db439e210ad7dcb4450_00d6b3670f0844c4bcaae3d48346deb5(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_7ad02c873b170db439e210ad7dcb4450()
        {
            bakedCommandBindings.Add("85bd350d218f4218b37f4460ad68e168", BakeCommandBinding__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168_CommandTarget = (global::PowerupCollectible)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"PowerupCollectible.CmdDisableCollectible",
            	"()",
            	SendCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168,
            	ReceiveLocalCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168,
            	MessageTarget.All,
            	_7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168(GenericCommandRequestArgs requestArgs)
        {
            var command = new _7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168(GenericCommandRequestArgs requestArgs)
        {
            var command = new _7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168(command);
        }

        private void ReceiveCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168(_7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168 command)
        {
			var target = _7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168_CommandTarget;
			target.CmdDisableCollectible();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168 castedCommand:
                    ReceiveCommand__7ad02c873b170db439e210ad7dcb4450_85bd350d218f4218b37f4460ad68e168(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_7ad02c873b170db439e210ad7dcb4450 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_7ad02c873b170db439e210ad7dcb4450>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
