// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1773dc540c6ae314e94cf5dc57ab2c93_0eac10bf4b764f95bf165271a102a19e : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1773dc540c6ae314e94cf5dc57ab2c93_7bfc54aeccab4bd6807408388b23ece9 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1773dc540c6ae314e94cf5dc57ab2c93_25e9e24ee7e44df7b8641b3dd0898ca6 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955);
        public override string CoherenceComponentName => "_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent).isBeingPushed;

            var simFrame = ((_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1773dc540c6ae314e94cf5dc57ab2c93_0806ce533d9a48fcb6d7dbd0744d665c : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955);
        public override string CoherenceComponentName => "_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent).isBeingPulled;

            var simFrame = ((_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1773dc540c6ae314e94cf5dc57ab2c93_50524e63651246289273ec01894984ae : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955);
        public override string CoherenceComponentName => "_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent).isFalling;

            var simFrame = ((_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1773dc540c6ae314e94cf5dc57ab2c93_382088147421316955();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_1773dc540c6ae314e94cf5dc57ab2c93 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_1773dc540c6ae314e94cf5dc57ab2c93>();
        
        private global::Obstacle _1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["0eac10bf4b764f95bf165271a102a19e"] = new Binding_1773dc540c6ae314e94cf5dc57ab2c93_0eac10bf4b764f95bf165271a102a19e(),
			["7bfc54aeccab4bd6807408388b23ece9"] = new Binding_1773dc540c6ae314e94cf5dc57ab2c93_7bfc54aeccab4bd6807408388b23ece9(),
			["25e9e24ee7e44df7b8641b3dd0898ca6"] = new Binding_1773dc540c6ae314e94cf5dc57ab2c93_25e9e24ee7e44df7b8641b3dd0898ca6(),
			["0806ce533d9a48fcb6d7dbd0744d665c"] = new Binding_1773dc540c6ae314e94cf5dc57ab2c93_0806ce533d9a48fcb6d7dbd0744d665c(),
			["50524e63651246289273ec01894984ae"] = new Binding_1773dc540c6ae314e94cf5dc57ab2c93_50524e63651246289273ec01894984ae(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_1773dc540c6ae314e94cf5dc57ab2c93()
        {
            bakedCommandBindings.Add("fea02029b0bd457f807ee946901f54ec", BakeCommandBinding__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec,
            	ReceiveLocalCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec,
            	MessageTarget.All,
            	_1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec(command);
        }

        private void ReceiveCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec(_1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec command)
        {
			var target = _1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec castedCommand:
                    ReceiveCommand__1773dc540c6ae314e94cf5dc57ab2c93_fea02029b0bd457f807ee946901f54ec(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_1773dc540c6ae314e94cf5dc57ab2c93 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_1773dc540c6ae314e94cf5dc57ab2c93>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
