// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3b78fc18984b2c24187cb88e0af2d2e1_a8ea25033d24460cb23368ec040e5b00 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3b78fc18984b2c24187cb88e0af2d2e1_ecc1da59da674494aebb051485e32167 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3b78fc18984b2c24187cb88e0af2d2e1_1407f802497c466782f59bd90117d79b : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132);
        public override string CoherenceComponentName => "_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent).isBeingPushed;

            var simFrame = ((_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3b78fc18984b2c24187cb88e0af2d2e1_ba8f9ca3209c4bc5a39d411e5fc587d0 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132);
        public override string CoherenceComponentName => "_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent).isBeingPulled;

            var simFrame = ((_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_3b78fc18984b2c24187cb88e0af2d2e1_58051708b75a498b9262702ea26d9189 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132);
        public override string CoherenceComponentName => "_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent).isFalling;

            var simFrame = ((_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _3b78fc18984b2c24187cb88e0af2d2e1_6999489270508138132();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_3b78fc18984b2c24187cb88e0af2d2e1 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_3b78fc18984b2c24187cb88e0af2d2e1>();
        
        private global::Obstacle _3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["a8ea25033d24460cb23368ec040e5b00"] = new Binding_3b78fc18984b2c24187cb88e0af2d2e1_a8ea25033d24460cb23368ec040e5b00(),
			["ecc1da59da674494aebb051485e32167"] = new Binding_3b78fc18984b2c24187cb88e0af2d2e1_ecc1da59da674494aebb051485e32167(),
			["1407f802497c466782f59bd90117d79b"] = new Binding_3b78fc18984b2c24187cb88e0af2d2e1_1407f802497c466782f59bd90117d79b(),
			["ba8f9ca3209c4bc5a39d411e5fc587d0"] = new Binding_3b78fc18984b2c24187cb88e0af2d2e1_ba8f9ca3209c4bc5a39d411e5fc587d0(),
			["58051708b75a498b9262702ea26d9189"] = new Binding_3b78fc18984b2c24187cb88e0af2d2e1_58051708b75a498b9262702ea26d9189(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_3b78fc18984b2c24187cb88e0af2d2e1()
        {
            bakedCommandBindings.Add("d79e32f337da48aaaebaeb9cf8840ecc", BakeCommandBinding__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc,
            	ReceiveLocalCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc,
            	MessageTarget.All,
            	_3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc(command);
        }

        private void ReceiveCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc(_3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc command)
        {
			var target = _3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc castedCommand:
                    ReceiveCommand__3b78fc18984b2c24187cb88e0af2d2e1_d79e32f337da48aaaebaeb9cf8840ecc(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_3b78fc18984b2c24187cb88e0af2d2e1 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_3b78fc18984b2c24187cb88e0af2d2e1>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
