// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1999ecd15ba513f4b823dfe669be1fa0_e657d04277c34515a5527b54a0c52374 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1999ecd15ba513f4b823dfe669be1fa0_069fc1cdab7442c091eec85583bed4e4 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1999ecd15ba513f4b823dfe669be1fa0_497f3f57094c4f9f95c73bdfb5f7c897 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703);
        public override string CoherenceComponentName => "_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent).isBeingPushed;

            var simFrame = ((_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1999ecd15ba513f4b823dfe669be1fa0_284115314472539703();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1999ecd15ba513f4b823dfe669be1fa0_38a475754f0d440d8b491072466fdc69 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703);
        public override string CoherenceComponentName => "_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent).isBeingPulled;

            var simFrame = ((_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1999ecd15ba513f4b823dfe669be1fa0_284115314472539703();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_1999ecd15ba513f4b823dfe669be1fa0_ef84eea5f8134f439ccd21e4f832871a : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703);
        public override string CoherenceComponentName => "_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent).isFalling;

            var simFrame = ((_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_1999ecd15ba513f4b823dfe669be1fa0_284115314472539703)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _1999ecd15ba513f4b823dfe669be1fa0_284115314472539703();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_1999ecd15ba513f4b823dfe669be1fa0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_1999ecd15ba513f4b823dfe669be1fa0>();
        
        private global::Obstacle _1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["e657d04277c34515a5527b54a0c52374"] = new Binding_1999ecd15ba513f4b823dfe669be1fa0_e657d04277c34515a5527b54a0c52374(),
			["069fc1cdab7442c091eec85583bed4e4"] = new Binding_1999ecd15ba513f4b823dfe669be1fa0_069fc1cdab7442c091eec85583bed4e4(),
			["497f3f57094c4f9f95c73bdfb5f7c897"] = new Binding_1999ecd15ba513f4b823dfe669be1fa0_497f3f57094c4f9f95c73bdfb5f7c897(),
			["38a475754f0d440d8b491072466fdc69"] = new Binding_1999ecd15ba513f4b823dfe669be1fa0_38a475754f0d440d8b491072466fdc69(),
			["ef84eea5f8134f439ccd21e4f832871a"] = new Binding_1999ecd15ba513f4b823dfe669be1fa0_ef84eea5f8134f439ccd21e4f832871a(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_1999ecd15ba513f4b823dfe669be1fa0()
        {
            bakedCommandBindings.Add("a7036859db974a24ac1fdcd50293db02", BakeCommandBinding__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02,
            	ReceiveLocalCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02,
            	MessageTarget.All,
            	_1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02(GenericCommandRequestArgs requestArgs)
        {
            var command = new _1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02(command);
        }

        private void ReceiveCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02(_1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02 command)
        {
			var target = _1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02 castedCommand:
                    ReceiveCommand__1999ecd15ba513f4b823dfe669be1fa0_a7036859db974a24ac1fdcd50293db02(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_1999ecd15ba513f4b823dfe669be1fa0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_1999ecd15ba513f4b823dfe669be1fa0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
