// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_aea07fdc951f73744bdeb8e29613ef06_7fe8b3e356334277b49679c84b846791 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_aea07fdc951f73744bdeb8e29613ef06_a8d97e6297e44895a6052a1738f478a5 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_aea07fdc951f73744bdeb8e29613ef06_ce10a20a34574bf59cdc982dd916119a : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396);
        public override string CoherenceComponentName => "_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent).isBeingPushed;

            var simFrame = ((_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _aea07fdc951f73744bdeb8e29613ef06_6620593189173925396();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_aea07fdc951f73744bdeb8e29613ef06_89518dded9254df4b2f7a36c43681a51 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396);
        public override string CoherenceComponentName => "_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent).isBeingPulled;

            var simFrame = ((_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _aea07fdc951f73744bdeb8e29613ef06_6620593189173925396();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_aea07fdc951f73744bdeb8e29613ef06_0a9b1e95d88140fb8ebd757a2c6641f5 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396);
        public override string CoherenceComponentName => "_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent).isFalling;

            var simFrame = ((_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_aea07fdc951f73744bdeb8e29613ef06_6620593189173925396)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _aea07fdc951f73744bdeb8e29613ef06_6620593189173925396();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_aea07fdc951f73744bdeb8e29613ef06 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_aea07fdc951f73744bdeb8e29613ef06>();
        
        private global::Obstacle _aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002_CommandTarget;
        private global::Obstacle _aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["7fe8b3e356334277b49679c84b846791"] = new Binding_aea07fdc951f73744bdeb8e29613ef06_7fe8b3e356334277b49679c84b846791(),
			["a8d97e6297e44895a6052a1738f478a5"] = new Binding_aea07fdc951f73744bdeb8e29613ef06_a8d97e6297e44895a6052a1738f478a5(),
			["ce10a20a34574bf59cdc982dd916119a"] = new Binding_aea07fdc951f73744bdeb8e29613ef06_ce10a20a34574bf59cdc982dd916119a(),
			["89518dded9254df4b2f7a36c43681a51"] = new Binding_aea07fdc951f73744bdeb8e29613ef06_89518dded9254df4b2f7a36c43681a51(),
			["0a9b1e95d88140fb8ebd757a2c6641f5"] = new Binding_aea07fdc951f73744bdeb8e29613ef06_0a9b1e95d88140fb8ebd757a2c6641f5(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_aea07fdc951f73744bdeb8e29613ef06()
        {
            bakedCommandBindings.Add("eaec2e1a08304a9ea68f4690da54d002", BakeCommandBinding__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002);
            bakedCommandBindings.Add("d8b59f6466ee42f8a9419bb9fe6a87d9", BakeCommandBinding__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002,
            	ReceiveLocalCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002,
            	MessageTarget.All,
            	_aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002(GenericCommandRequestArgs requestArgs)
        {
            var command = new _aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002(GenericCommandRequestArgs requestArgs)
        {
            var command = new _aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002(command);
        }

        private void ReceiveCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002(_aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002 command)
        {
			var target = _aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9,
            	ReceiveLocalCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9,
            	MessageTarget.All,
            	_aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9(GenericCommandRequestArgs requestArgs)
        {
            var command = new _aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9(GenericCommandRequestArgs requestArgs)
        {
            var command = new _aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9(command);
        }

        private void ReceiveCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9(_aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9 command)
        {
			var target = _aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002 castedCommand:
                    ReceiveCommand__aea07fdc951f73744bdeb8e29613ef06_eaec2e1a08304a9ea68f4690da54d002(castedCommand);
                    break;
                case _aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9 castedCommand:
                    ReceiveCommand__aea07fdc951f73744bdeb8e29613ef06_d8b59f6466ee42f8a9419bb9fe6a87d9(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_aea07fdc951f73744bdeb8e29613ef06 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_aea07fdc951f73744bdeb8e29613ef06>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
