// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_ea922d1ff90d2ed45910371a1ad6f579_14da5d9dcfb54243a2a32f2f504b16d9 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_ea922d1ff90d2ed45910371a1ad6f579_ee2a24cbefb241d5ad79f761708af7e3 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_ea922d1ff90d2ed45910371a1ad6f579_56d29d1db26947d0972c16f567e7a6a8 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938);
        public override string CoherenceComponentName => "_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent).isBeingPushed;

            var simFrame = ((_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _ea922d1ff90d2ed45910371a1ad6f579_921896712208685938();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_ea922d1ff90d2ed45910371a1ad6f579_832d0fd45bf743ed8e080742cae78894 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938);
        public override string CoherenceComponentName => "_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent).isBeingPulled;

            var simFrame = ((_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _ea922d1ff90d2ed45910371a1ad6f579_921896712208685938();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_ea922d1ff90d2ed45910371a1ad6f579_e839e33529ac4335a3b13150e09225a9 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938);
        public override string CoherenceComponentName => "_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent).isFalling;

            var simFrame = ((_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_ea922d1ff90d2ed45910371a1ad6f579_921896712208685938)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _ea922d1ff90d2ed45910371a1ad6f579_921896712208685938();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_ea922d1ff90d2ed45910371a1ad6f579 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_ea922d1ff90d2ed45910371a1ad6f579>();
        
        private global::Obstacle _ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e_CommandTarget;
        private global::Obstacle _ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["14da5d9dcfb54243a2a32f2f504b16d9"] = new Binding_ea922d1ff90d2ed45910371a1ad6f579_14da5d9dcfb54243a2a32f2f504b16d9(),
			["ee2a24cbefb241d5ad79f761708af7e3"] = new Binding_ea922d1ff90d2ed45910371a1ad6f579_ee2a24cbefb241d5ad79f761708af7e3(),
			["56d29d1db26947d0972c16f567e7a6a8"] = new Binding_ea922d1ff90d2ed45910371a1ad6f579_56d29d1db26947d0972c16f567e7a6a8(),
			["832d0fd45bf743ed8e080742cae78894"] = new Binding_ea922d1ff90d2ed45910371a1ad6f579_832d0fd45bf743ed8e080742cae78894(),
			["e839e33529ac4335a3b13150e09225a9"] = new Binding_ea922d1ff90d2ed45910371a1ad6f579_e839e33529ac4335a3b13150e09225a9(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_ea922d1ff90d2ed45910371a1ad6f579()
        {
            bakedCommandBindings.Add("a01c8c9b1be6487e809f3b481cbb745e", BakeCommandBinding__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e);
            bakedCommandBindings.Add("065d7306ceb640a39d6376cf9f2dfce7", BakeCommandBinding__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e,
            	ReceiveLocalCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e,
            	MessageTarget.All,
            	_ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e(command);
        }

        private void ReceiveCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e(_ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e command)
        {
			var target = _ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7,
            	ReceiveLocalCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7,
            	MessageTarget.All,
            	_ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7(command);
        }

        private void ReceiveCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7(_ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7 command)
        {
			var target = _ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e castedCommand:
                    ReceiveCommand__ea922d1ff90d2ed45910371a1ad6f579_a01c8c9b1be6487e809f3b481cbb745e(castedCommand);
                    break;
                case _ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7 castedCommand:
                    ReceiveCommand__ea922d1ff90d2ed45910371a1ad6f579_065d7306ceb640a39d6376cf9f2dfce7(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_ea922d1ff90d2ed45910371a1ad6f579 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_ea922d1ff90d2ed45910371a1ad6f579>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
