// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_e24ad073b46134647ad5c02476238e40_2b49ed059bc64dbabe87c3e471665f36 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_e24ad073b46134647ad5c02476238e40_77b95c9ccf0e4c44b316610a20c79fc4 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_e24ad073b46134647ad5c02476238e40_fef0dc39dd6a40b8ae291c68746fc74c : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_e24ad073b46134647ad5c02476238e40_7618071522980441646);
        public override string CoherenceComponentName => "_e24ad073b46134647ad5c02476238e40_7618071522980441646";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent).isBeingPushed;

            var simFrame = ((_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _e24ad073b46134647ad5c02476238e40_7618071522980441646();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_e24ad073b46134647ad5c02476238e40_2db1db46b4534e8587da43b6a045f063 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_e24ad073b46134647ad5c02476238e40_7618071522980441646);
        public override string CoherenceComponentName => "_e24ad073b46134647ad5c02476238e40_7618071522980441646";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent).isBeingPulled;

            var simFrame = ((_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _e24ad073b46134647ad5c02476238e40_7618071522980441646();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_e24ad073b46134647ad5c02476238e40_c881f758f6d24729be653f1a4ded7241 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_e24ad073b46134647ad5c02476238e40_7618071522980441646);
        public override string CoherenceComponentName => "_e24ad073b46134647ad5c02476238e40_7618071522980441646";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent).isFalling;

            var simFrame = ((_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_e24ad073b46134647ad5c02476238e40_7618071522980441646)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _e24ad073b46134647ad5c02476238e40_7618071522980441646();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_e24ad073b46134647ad5c02476238e40 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_e24ad073b46134647ad5c02476238e40>();
        
        private global::Obstacle _e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc_CommandTarget;
        private global::Obstacle _e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["2b49ed059bc64dbabe87c3e471665f36"] = new Binding_e24ad073b46134647ad5c02476238e40_2b49ed059bc64dbabe87c3e471665f36(),
			["77b95c9ccf0e4c44b316610a20c79fc4"] = new Binding_e24ad073b46134647ad5c02476238e40_77b95c9ccf0e4c44b316610a20c79fc4(),
			["fef0dc39dd6a40b8ae291c68746fc74c"] = new Binding_e24ad073b46134647ad5c02476238e40_fef0dc39dd6a40b8ae291c68746fc74c(),
			["2db1db46b4534e8587da43b6a045f063"] = new Binding_e24ad073b46134647ad5c02476238e40_2db1db46b4534e8587da43b6a045f063(),
			["c881f758f6d24729be653f1a4ded7241"] = new Binding_e24ad073b46134647ad5c02476238e40_c881f758f6d24729be653f1a4ded7241(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_e24ad073b46134647ad5c02476238e40()
        {
            bakedCommandBindings.Add("c2563528befc4a77b5d7bf7229bb52fc", BakeCommandBinding__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc);
            bakedCommandBindings.Add("947fdc80f412467da4543c5cf30f865c", BakeCommandBinding__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc,
            	ReceiveLocalCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc,
            	MessageTarget.All,
            	_e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc(command);
        }

        private void ReceiveCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc(_e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc command)
        {
			var target = _e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c,
            	ReceiveLocalCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c,
            	MessageTarget.All,
            	_e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c(GenericCommandRequestArgs requestArgs)
        {
            var command = new _e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c(command);
        }

        private void ReceiveCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c(_e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c command)
        {
			var target = _e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc castedCommand:
                    ReceiveCommand__e24ad073b46134647ad5c02476238e40_c2563528befc4a77b5d7bf7229bb52fc(castedCommand);
                    break;
                case _e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c castedCommand:
                    ReceiveCommand__e24ad073b46134647ad5c02476238e40_947fdc80f412467da4543c5cf30f865c(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_e24ad073b46134647ad5c02476238e40 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_e24ad073b46134647ad5c02476238e40>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
