// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_4a0ebe817580b2446862a2ecd338a034_2de484e397304eb79f904c215199d51d : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_4a0ebe817580b2446862a2ecd338a034 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_4a0ebe817580b2446862a2ecd338a034>();
        
        private global::LevelGoal _4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301_CommandTarget;
        private global::LevelGoal _4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["2de484e397304eb79f904c215199d51d"] = new Binding_4a0ebe817580b2446862a2ecd338a034_2de484e397304eb79f904c215199d51d(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_4a0ebe817580b2446862a2ecd338a034()
        {
            bakedCommandBindings.Add("7be96ea70f5942c580289a9fe72be301", BakeCommandBinding__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301);
            bakedCommandBindings.Add("6d8d0fbfae22451b8ab2aaeeb1e90ebc", BakeCommandBinding__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301_CommandTarget = (global::LevelGoal)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"LevelGoal.CmdLoseLevel",
            	"()",
            	SendCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301,
            	ReceiveLocalCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301,
            	MessageTarget.All,
            	_4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301(GenericCommandRequestArgs requestArgs)
        {
            var command = new _4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301(GenericCommandRequestArgs requestArgs)
        {
            var command = new _4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301(command);
        }

        private void ReceiveCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301(_4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301 command)
        {
			var target = _4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301_CommandTarget;
			target.CmdLoseLevel();
        }
        private void BakeCommandBinding__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc_CommandTarget = (global::LevelGoal)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"LevelGoal.CmdWinLevel",
            	"()",
            	SendCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc,
            	ReceiveLocalCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc,
            	MessageTarget.All,
            	_4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc(GenericCommandRequestArgs requestArgs)
        {
            var command = new _4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc(command);
        }

        private void ReceiveCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc(_4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc command)
        {
			var target = _4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc_CommandTarget;
			target.CmdWinLevel();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301 castedCommand:
                    ReceiveCommand__4a0ebe817580b2446862a2ecd338a034_7be96ea70f5942c580289a9fe72be301(castedCommand);
                    break;
                case _4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc castedCommand:
                    ReceiveCommand__4a0ebe817580b2446862a2ecd338a034_6d8d0fbfae22451b8ab2aaeeb1e90ebc(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_4a0ebe817580b2446862a2ecd338a034 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_4a0ebe817580b2446862a2ecd338a034>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
