// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_718e1373f11cd9143bb823ab01bd209a_8b9c0573a8bb40e3a9099fdaa7d7e889 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_718e1373f11cd9143bb823ab01bd209a_19b1106371b64e0680e728c101688b13 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_718e1373f11cd9143bb823ab01bd209a_5373e10f8c284e539da7918131767ba3 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_718e1373f11cd9143bb823ab01bd209a_7633055719913054959);
        public override string CoherenceComponentName => "_718e1373f11cd9143bb823ab01bd209a_7633055719913054959";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPushed); }
            set { CastedUnityComponent.isBeingPushed = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent).isBeingPushed;

            var simFrame = ((_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent).isBeingPushedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPushed = Value;
            }
            else
            {
                update.isBeingPushed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPushedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _718e1373f11cd9143bb823ab01bd209a_7633055719913054959();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_718e1373f11cd9143bb823ab01bd209a_340472b3afda4a53b77a40a5b1e42b0e : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_718e1373f11cd9143bb823ab01bd209a_7633055719913054959);
        public override string CoherenceComponentName => "_718e1373f11cd9143bb823ab01bd209a_7633055719913054959";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isBeingPulled); }
            set { CastedUnityComponent.isBeingPulled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent).isBeingPulled;

            var simFrame = ((_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent).isBeingPulledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isBeingPulled = Value;
            }
            else
            {
                update.isBeingPulled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isBeingPulledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _718e1373f11cd9143bb823ab01bd209a_7633055719913054959();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_718e1373f11cd9143bb823ab01bd209a_fd5c86fe063744918e174128f56fee01 : BoolBinding
    {   
        private global::Obstacle CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Obstacle)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_718e1373f11cd9143bb823ab01bd209a_7633055719913054959);
        public override string CoherenceComponentName => "_718e1373f11cd9143bb823ab01bd209a_7633055719913054959";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isFalling); }
            set { CastedUnityComponent.isFalling = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent).isFalling;

            var simFrame = ((_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent).isFallingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_718e1373f11cd9143bb823ab01bd209a_7633055719913054959)coherenceComponent;
            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                update.isFalling = Value;
            }
            else
            {
                update.isFalling = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isFallingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _718e1373f11cd9143bb823ab01bd209a_7633055719913054959();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_718e1373f11cd9143bb823ab01bd209a : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_718e1373f11cd9143bb823ab01bd209a>();
        
        private global::Obstacle _718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b_CommandTarget;
        private global::Obstacle _718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["8b9c0573a8bb40e3a9099fdaa7d7e889"] = new Binding_718e1373f11cd9143bb823ab01bd209a_8b9c0573a8bb40e3a9099fdaa7d7e889(),
			["19b1106371b64e0680e728c101688b13"] = new Binding_718e1373f11cd9143bb823ab01bd209a_19b1106371b64e0680e728c101688b13(),
			["5373e10f8c284e539da7918131767ba3"] = new Binding_718e1373f11cd9143bb823ab01bd209a_5373e10f8c284e539da7918131767ba3(),
			["340472b3afda4a53b77a40a5b1e42b0e"] = new Binding_718e1373f11cd9143bb823ab01bd209a_340472b3afda4a53b77a40a5b1e42b0e(),
			["fd5c86fe063744918e174128f56fee01"] = new Binding_718e1373f11cd9143bb823ab01bd209a_fd5c86fe063744918e174128f56fee01(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_718e1373f11cd9143bb823ab01bd209a()
        {
            bakedCommandBindings.Add("9eed837e83704da1b1e5bd213f139c1b", BakeCommandBinding__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b);
            bakedCommandBindings.Add("0df5a39b1f4e46a8a35c8404452dd62c", BakeCommandBinding__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdPlayFallLanding",
            	"(UnityEngine.Vector3)",
            	SendCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b,
            	ReceiveLocalCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b,
            	MessageTarget.All,
            	_718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.landPosition = (UnityEngine.Vector3)requestArgs.Args[0];

            ReceiveCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b(command);
        }

        private void ReceiveCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b(_718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b command)
        {
			var target = _718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b_CommandTarget;
			target.CmdPlayFallLanding((UnityEngine.Vector3)(command.landPosition));
        }
        private void BakeCommandBinding__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c_CommandTarget = (global::Obstacle)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Obstacle.CmdDestroyObstacle",
            	"(System.Int32)",
            	SendCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c,
            	ReceiveLocalCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c,
            	MessageTarget.All,
            	_718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c(GenericCommandRequestArgs requestArgs)
        {
            var command = new _718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.source = (System.Int32)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c(GenericCommandRequestArgs requestArgs)
        {
            var command = new _718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.source = (System.Int32)requestArgs.Args[0];

            ReceiveCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c(command);
        }

        private void ReceiveCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c(_718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c command)
        {
			var target = _718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c_CommandTarget;
			target.CmdDestroyObstacle((System.Int32)(command.source));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b castedCommand:
                    ReceiveCommand__718e1373f11cd9143bb823ab01bd209a_9eed837e83704da1b1e5bd213f139c1b(castedCommand);
                    break;
                case _718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c castedCommand:
                    ReceiveCommand__718e1373f11cd9143bb823ab01bd209a_0df5a39b1f4e46a8a35c8404452dd62c(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_718e1373f11cd9143bb823ab01bd209a Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_718e1373f11cd9143bb823ab01bd209a>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
