// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Connection;
    using Coherence.Entities;
    using Coherence.Serializer;
    using Coherence.Log;
    using Coherence.SimulationFrame;


    [UnityEngine.Scripting.Preserve]

    [System.Serializable]
    public class Definition : IDefinition
    {
        public const string schemaId = "a634af0304e421ea63e78b14e47f1b9eee010973";
        public const uint InternalWorldPosition = 0;
        public const uint InternalWorldOrientation = 1;
        public const uint InternalLocalUserComponent = 2;
        public const uint InternalWorldPositionQuery = 3;
        public const uint InternalArchetypeComponent = 4;
        public const uint InternalPersistence = 5;
        public const uint InternalConnectedEntity = 6;
        public const uint InternalUniqueID = 7;
        public const uint InternalConnection = 8;
        public const uint InternalConnectionScene = 9;
        public const uint InternalGlobal = 10;
        public const uint InternalGlobalQuery = 11;
        public const uint InternalTag = 12;
        public const uint InternalTagQuery = 13;
        public const uint InternalPreserveChildren = 14;
        public const uint InternalScene = 15;
        public const uint InternalAssetId = 16;
        public const uint InternalGenericScale = 17;
        public const uint Internal_0c583654429fe8541b706485a9d9e726_7768126713293784213 = 18;
        public const uint Internal_21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534 = 19;
        public const uint Internal_9d2e9d257e8387b45979b55403f8a357_2197336975981693810 = 20;
        public const uint Internal_a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988 = 21;
        public const uint Internal_b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430 = 22;
        public const uint InternalAuthorityRequest = 0;
        public const uint InternalAuthorityTransfer = 1;
        public const uint InternalQuerySynced = 2;
        public const uint InternalAdoptOrphan = 3;
        public const uint InternalPersistenceReady = 4;
        public const uint InternalSceneIndexChanged = 5;
        public const uint Internal_0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d = 6;
        public const uint Internal_0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3 = 7;
        public const uint Internal_21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c = 8;
        public const uint Internal_21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5 = 9;
        public const uint Internal_36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27 = 10;
        public const uint Internal_9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101 = 11;
        public const uint Internal_9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7 = 12;
        public const uint Internal_9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a = 13;
        public const uint Internal_9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029 = 14;
        public const uint Internal_a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d = 15;
        public const uint Internal_a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40 = 16;
        public const uint Internal_b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6 = 17;
        public const uint Internal_b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e = 18;

        private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>()
        {
            { 0, "WorldPosition" },
            { 1, "WorldOrientation" },
            { 2, "LocalUserComponent" },
            { 3, "WorldPositionQuery" },
            { 4, "ArchetypeComponent" },
            { 5, "Persistence" },
            { 6, "ConnectedEntity" },
            { 7, "UniqueID" },
            { 8, "Connection" },
            { 9, "ConnectionScene" },
            { 10, "Global" },
            { 11, "GlobalQuery" },
            { 12, "Tag" },
            { 13, "TagQuery" },
            { 14, "PreserveChildren" },
            { 15, "Scene" },
            { 16, "AssetId" },
            { 17, "GenericScale" },
            { 18, "_0c583654429fe8541b706485a9d9e726_7768126713293784213" },
            { 19, "_21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534" },
            { 20, "_9d2e9d257e8387b45979b55403f8a357_2197336975981693810" },
            { 21, "_a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988" },
            { 22, "_b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430" },
        };

        public static string ComponentNameForTypeId(uint typeId)
        {
            if (componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
            {
                return componentName;
            }
            else
            {
                return "";
            }
        }

        public static readonly Dictionary<uint, MessageTarget> CommandRoutingByType = new Dictionary<uint, MessageTarget>()
        {
            { Definition.InternalAuthorityRequest , MessageTarget.All },
            { Definition.InternalAuthorityTransfer , MessageTarget.All },
            { Definition.InternalQuerySynced , MessageTarget.All },
            { Definition.InternalAdoptOrphan , MessageTarget.All },
            { Definition.InternalPersistenceReady , MessageTarget.All },
            { Definition.InternalSceneIndexChanged , MessageTarget.All },
            { Definition.Internal_0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d , MessageTarget.All },
            { Definition.Internal_0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3 , MessageTarget.All },
            { Definition.Internal_21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c , MessageTarget.All },
            { Definition.Internal_21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5 , MessageTarget.All },
            { Definition.Internal_36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27 , MessageTarget.All },
            { Definition.Internal_9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101 , MessageTarget.All },
            { Definition.Internal_9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7 , MessageTarget.All },
            { Definition.Internal_9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a , MessageTarget.All },
            { Definition.Internal_9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029 , MessageTarget.All },
            { Definition.Internal_a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d , MessageTarget.All },
            { Definition.Internal_a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40 , MessageTarget.All },
            { Definition.Internal_b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6 , MessageTarget.All },
            { Definition.Internal_b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e , MessageTarget.All },
        };

        public ICoherenceComponentData ReadComponentUpdate(uint componentType, AbsoluteSimulationFrame referenceSimulationFrame,
            IInBitStream bitStream, Logger logger)
        {
            var inProtocolStream = new InProtocolBitStream(bitStream);

            switch (componentType)
            {
                case InternalWorldPosition:
                    return WorldPosition.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldOrientation:
                    return WorldOrientation.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPersistence:
                    return Persistence.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectedEntity:
                    return ConnectedEntity.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalUniqueID:
                    return UniqueID.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnection:
                    return Connection.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectionScene:
                    return ConnectionScene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobal:
                    return Global.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobalQuery:
                    return GlobalQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTag:
                    return Tag.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTagQuery:
                    return TagQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPreserveChildren:
                    return PreserveChildren.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalScene:
                    return Scene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalAssetId:
                    return AssetId.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGenericScale:
                    return GenericScale.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_0c583654429fe8541b706485a9d9e726_7768126713293784213:
                    return _0c583654429fe8541b706485a9d9e726_7768126713293784213.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534:
                    return _21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_9d2e9d257e8387b45979b55403f8a357_2197336975981693810:
                    return _9d2e9d257e8387b45979b55403f8a357_2197336975981693810.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988:
                    return _a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430:
                    return _b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430.Deserialize(referenceSimulationFrame, inProtocolStream);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(componentType),
                        $"Missing serialization implementation for a component: {componentType}");
            }
        }

        public uint WriteComponentUpdate(ICoherenceComponentData data, uint serializeAs, bool isRefSimFrameValid,
            AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream protocolStream, Logger logger)
        {
            switch (serializeAs)
            {
                case InternalWorldPosition:
                    return WorldPosition.Serialize((WorldPosition)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldOrientation:
                    return WorldOrientation.Serialize((WorldOrientation)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Serialize((LocalUserComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Serialize((WorldPositionQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Serialize((ArchetypeComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPersistence:
                    return Persistence.Serialize((Persistence)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectedEntity:
                    return ConnectedEntity.Serialize((ConnectedEntity)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalUniqueID:
                    return UniqueID.Serialize((UniqueID)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnection:
                    return Connection.Serialize((Connection)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectionScene:
                    return ConnectionScene.Serialize((ConnectionScene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobal:
                    return Global.Serialize((Global)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobalQuery:
                    return GlobalQuery.Serialize((GlobalQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTag:
                    return Tag.Serialize((Tag)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTagQuery:
                    return TagQuery.Serialize((TagQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPreserveChildren:
                    return PreserveChildren.Serialize((PreserveChildren)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalScene:
                    return Scene.Serialize((Scene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalAssetId:
                    return AssetId.Serialize((AssetId)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGenericScale:
                    return GenericScale.Serialize((GenericScale)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_0c583654429fe8541b706485a9d9e726_7768126713293784213:
                    return _0c583654429fe8541b706485a9d9e726_7768126713293784213.Serialize((_0c583654429fe8541b706485a9d9e726_7768126713293784213)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534:
                    return _21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534.Serialize((_21d4cb6b7c9058e408bd83c1de5c665d_922907733723194534)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_9d2e9d257e8387b45979b55403f8a357_2197336975981693810:
                    return _9d2e9d257e8387b45979b55403f8a357_2197336975981693810.Serialize((_9d2e9d257e8387b45979b55403f8a357_2197336975981693810)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988:
                    return _a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988.Serialize((_a5d9da17a1ed97b4fa7c98cdaa006362_8348739996926226988)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430:
                    return _b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430.Serialize((_b0243204ed9377a43aa1829a8c0a31a5_4607376809830200430)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingComponentImplementation, ("component", data.GetComponentType()));
                    return 0;
            }
        }

        public IEntityCommand ReadCommand(uint commandType, Entity entity, MessageTarget target, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    return AuthorityRequest.Deserialize(bitStream, entity, target);
                case Definition.InternalAuthorityTransfer:
                    return AuthorityTransfer.Deserialize(bitStream, entity, target);
                case Definition.InternalQuerySynced:
                    return QuerySynced.Deserialize(bitStream, entity, target);
                case Definition.InternalAdoptOrphan:
                    return AdoptOrphan.Deserialize(bitStream, entity, target);
                case Definition.InternalPersistenceReady:
                    return PersistenceReady.Deserialize(bitStream, entity, target);
                case Definition.InternalSceneIndexChanged:
                    return SceneIndexChanged.Deserialize(bitStream, entity, target);
                case Definition.Internal_0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d:
                    return _0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d.Deserialize(bitStream, entity, target);
                case Definition.Internal_0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3:
                    return _0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3.Deserialize(bitStream, entity, target);
                case Definition.Internal_21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c:
                    return _21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c.Deserialize(bitStream, entity, target);
                case Definition.Internal_21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5:
                    return _21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5.Deserialize(bitStream, entity, target);
                case Definition.Internal_36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27:
                    return _36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27.Deserialize(bitStream, entity, target);
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101:
                    return _9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101.Deserialize(bitStream, entity, target);
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7:
                    return _9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7.Deserialize(bitStream, entity, target);
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a:
                    return _9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a.Deserialize(bitStream, entity, target);
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029:
                    return _9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029.Deserialize(bitStream, entity, target);
                case Definition.Internal_a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d:
                    return _a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d.Deserialize(bitStream, entity, target);
                case Definition.Internal_a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40:
                    return _a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40.Deserialize(bitStream, entity, target);
                case Definition.Internal_b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6:
                    return _b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6.Deserialize(bitStream, entity, target);
                case Definition.Internal_b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e:
                    return _b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e.Deserialize(bitStream, entity, target);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(commandType),
                        $"Missing serialization implementation for a command: {commandType}");
            }
        }

        public IEntityInput ReadInput(uint inputType, Entity entity, long frame, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (inputType)
            {
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(inputType),
                        $"Missing serialization implementation for an input: {inputType}");
            }
        }

        public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
                    break;
                case Definition.InternalAuthorityTransfer:
                    AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
                    break;
                case Definition.InternalQuerySynced:
                    QuerySynced.Serialize((QuerySynced)data, bitStream);
                    break;
                case Definition.InternalAdoptOrphan:
                    AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
                    break;
                case Definition.InternalPersistenceReady:
                    PersistenceReady.Serialize((PersistenceReady)data, bitStream);
                    break;
                case Definition.InternalSceneIndexChanged:
                    SceneIndexChanged.Serialize((SceneIndexChanged)data, bitStream);
                    break;
                case Definition.Internal_0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d:
                    _0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d.Serialize((_0c583654429fe8541b706485a9d9e726_73518623a8a14628a1a93d387bb4306d)data, bitStream);
                    break;
                case Definition.Internal_0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3:
                    _0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3.Serialize((_0c583654429fe8541b706485a9d9e726_a83b0fb7cf0f47c1aeed078b42eca0e3)data, bitStream);
                    break;
                case Definition.Internal_21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c:
                    _21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c.Serialize((_21d4cb6b7c9058e408bd83c1de5c665d_715264e40e424631b12d8b8d91b22a2c)data, bitStream);
                    break;
                case Definition.Internal_21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5:
                    _21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5.Serialize((_21d4cb6b7c9058e408bd83c1de5c665d_dd5abb8a8ec6466886ce36af5ae7e8f5)data, bitStream);
                    break;
                case Definition.Internal_36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27:
                    _36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27.Serialize((_36277b2db15074b4b973a36e96eb7272_8e3cf9e0383b4a5397f446e9dbe0fd27)data, bitStream);
                    break;
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101:
                    _9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101.Serialize((_9d2e9d257e8387b45979b55403f8a357_52ff7f68ff08497698e497f264cb1101)data, bitStream);
                    break;
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7:
                    _9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7.Serialize((_9d2e9d257e8387b45979b55403f8a357_7ba9f3d1b98f4f79a94456ff96d28ce7)data, bitStream);
                    break;
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a:
                    _9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a.Serialize((_9d2e9d257e8387b45979b55403f8a357_874ab9ae8f1b42c58c9e6518d081fb9a)data, bitStream);
                    break;
                case Definition.Internal_9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029:
                    _9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029.Serialize((_9d2e9d257e8387b45979b55403f8a357_cc38682f1af84d309a4f8900961f4029)data, bitStream);
                    break;
                case Definition.Internal_a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d:
                    _a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d.Serialize((_a5d9da17a1ed97b4fa7c98cdaa006362_ebfe87c43d2c4172b7c880ec9197685d)data, bitStream);
                    break;
                case Definition.Internal_a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40:
                    _a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40.Serialize((_a5d9da17a1ed97b4fa7c98cdaa006362_fd8514ee76e24668a0c7e6bc4efc9f40)data, bitStream);
                    break;
                case Definition.Internal_b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6:
                    _b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6.Serialize((_b0243204ed9377a43aa1829a8c0a31a5_0c5b59ee7c2546eda9ee2bad6363b7f6)data, bitStream);
                    break;
                case Definition.Internal_b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e:
                    _b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e.Serialize((_b0243204ed9377a43aa1829a8c0a31a5_aa2b1d0867df45c587fd63e628c9d46e)data, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingCommandImplementation, ("command", commandType));
                    break;
            }
        }

        public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
        {
            var inputData = (InputData)data;

            switch (inputType)
            {
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingInputImplementation, ("input", inputType));
                    break;
            }
        }

        public IEntityCommand CreateAuthorityRequest(Entity entity, ClientID requester, AuthorityType authType)
        {
            return new AuthorityRequest(entity, (uint)requester, (int)authType)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public IEntityCommand CreateAdoptOrphanCommand(Entity entity)
        {
            return new AdoptOrphan
            {
                Entity = entity,
                Target = MessageTarget.StateAuthorityOnly,
            };
        }

        public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand,
            out ClientID requester, out AuthorityType authType)
        {
            if (entityCommand is AuthorityRequest request)
            {
                requester = (ClientID)request.requester;
                authType = (AuthorityType)request.authorityType;

                return true;
            }

            requester = default;
            authType = default;

            return false;
        }

        public IEntityCommand CreateAuthorityTransfer(Entity entity, ClientID newAuthority, bool accepted, AuthorityType authType)
        {
            return new AuthorityTransfer(entity, (uint)newAuthority, accepted, (int)authType)
			{
				Target = MessageTarget.Other,
			};
        }

        public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
            out bool transferAccepted, out AuthorityType authType)
        {
            if (entityCommand is AuthorityTransfer transfer)
            {
                newAuthority = (ClientID)transfer.newAuthority;
                transferAccepted = transfer.accepted;
                authType = (AuthorityType)transfer.authorityType;

                return true;
            }

            newAuthority = default;
            transferAccepted = default;
            authType = default;

            return false;
        }

        public ICoherenceComponentData GeneratePersistenceData()
        {
            var persistence = new Persistence();

            return persistence;
        }

        public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid, AbsoluteSimulationFrame simFrame)
        {
            var uniqueID = new UniqueID();
            uniqueID.uuid = uuid;
            uniqueID.uuidSimulationFrame = simFrame;
            uniqueID.FieldsMask = 0b1;

            return uniqueID;
        }

        public ICoherenceComponentData CreateGlobalComponent()
        {
            return new Global();
        }

        public ICoherenceComponentData GenerateGlobalQueryComponent()
        {
            return new GlobalQuery();
        }

        public string ExtractCoherenceUUID(ICoherenceComponentData data)
        {
            var uniqueID = (UniqueID)data;
            return uniqueID.uuid;
        }

        public bool IsConnectedEntity(ICoherenceComponentData data)
        {
            return data.GetComponentType() == Definition.InternalConnectedEntity;
        }

        public Entity ExtractConnectedEntityID(ICoherenceComponentData data)
        {
            var connectedEntity = (ConnectedEntity)data;

            return connectedEntity.value;
        }

        public string ExtractCoherenceTag(ICoherenceComponentData data)
        {
            var tag = (Tag)data;
            return tag.tag;
        }

        public bool TryGetSceneIndexChangedCommand(IEntityCommand entityCommand, out int sceneIndex)
        {
            if (entityCommand is SceneIndexChanged changed)
            {
                sceneIndex = (int)changed.sceneIndex;

                return true;
            }

            sceneIndex = default;

            return false;
        }

        public IEntityCommand CreateSceneIndexChangedCommand(Entity entity, int sceneIndex)
        {
            return new SceneIndexChanged(entity, sceneIndex)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public bool IsSendOrderedComponent(uint componentID)
        {
            switch(componentID)
            {
                case 6:
                    return true;
                default:
                    return false;
            }
        }
}


}
